override:
    ci.pr.max_lines_changed: 1000
    ci.php.matrix: ["8.3", "8.4", "8.5"]
    typos.exclude: ["docs/"]
    phpunit.php_options: "-d memory_limit=512M"
    phpunit.testsuites.integration: []
    phpmetrics.complexity.max_weighted_methods_per_class: 40
    sonar.exclusions: ["../../tests/**"]

append:
    phpstan.neon_includes:
        - "../../rules.neon"
        - "../../phpstan-self.neon"
